USE [MLSLoad]
GO

SET ansi_nulls ON
GO
SET quoted_identifier ON
GO
-- =============================================
-- Author:		Randall Gonzalez
-- Create date: 01-29-2021
-- Description:	Drops/creates MLS Listings tables that are sqooped from HDFS
-- =============================================
CREATE OR ALTER PROCEDURE [dbo].[MLS_Listings_CreateTablesForSqoop_sp]
AS
BEGIN

	SET NOCOUNT ON;

	-- #### Listings_sqoop

	DROP TABLE IF EXISTS [dbo].[Listings_sqoop]
	CREATE TABLE [dbo].[Listings_sqoop](
		created_datetime datetime,
		mls_listing_id varchar(50),
		street_address varchar(100),
		unit_type varchar(10),
		unit varchar(30),
		city varchar(100),		
		[state] char(2),		
		zip varchar(5),
		latitude decimal(9,6),
		longitude decimal(9,6),
		legal_description varchar(max),
		subdivision varchar(100),
		lot varchar(15),
		block varchar(15),
		legal_tract varchar(10),
		book varchar(25),
		[section] varchar(2),
		township varchar(3),
		[range] varchar(3),
		apn varchar(100),
		county_name varchar(50),
		fips varchar(5),
		census_tract_geo_id varchar(11),
		school_district varchar(125),
		property_type char(2),
		property_sub_type varchar(20),
		property_description varchar(500),
		lot_size_acres decimal(16,4),
		lot_size_sq_ft decimal(16,4),
		zoning varchar(250),
		restrictions varchar(250),
		easements varchar(250),
		water_source varchar(20),
		septic_sewer varchar(6),
		sfha char(1),
		gated_community char(1),
		hoa char(1),
		hoa_name varchar(150),
		hoa_management_co varchar(250),
		hoa_management_co_phone varchar(10),
		occupant_type varchar(25),
		ownership_type varchar(20),
		owner_type varchar(25),
		owner_name varchar(255),
		owner_phone varchar(10),
		year_built smallint,
		year_updated smallint,
		number_of_units int,
		living_area_sq_ft decimal(16,4),
		living_area_sq_ft_source varchar(25),
		building_style varchar(100),
		stories decimal(8,4),
		beds int,
		full_baths int,
		half_baths int,
		basement char(1),
		finished_basement_pct decimal(8,4),
		garage_type char(1),
		garage_style varchar(100),
		garage_spaces decimal(16,4),
		roof_type varchar(255),
		exterior_material varchar(255),
		foundation varchar(255),
		pool varchar(100),
		condition varchar(250),
		property_tax_appraisal decimal(16,4),
		property_tax decimal(16,4),
		property_tax_year smallint,
		hoa_dues decimal(16,4),
		hoa_dues_frequency int,
		hoa_dues_description varchar(750),
		rent_sale varchar(20),
		entry_date date,
		listing_date date,
		listing_status char(1),
		listing_status_detail varchar(50),
		status_date date,
		current_price decimal(16,4),
		current_price_as_of_date date,
		orig_price decimal(16,4),
		orig_listing_date date,
		contract_date date,
		closed_price decimal(16,4),
		closed_date date,
		days_on_market int,
		dom_date datetime,
		cumulative_days_on_market int,
		sale_circumstances varchar(max),
		listing_conditions varchar(max),
		listing_url varchar(250),
		listing_image_url varchar(max),
		listing_image_url_count int,
		listing_image_url_date date,
		loan_amount decimal(16,4),
		public_remarks varchar(max),
		realtor_remarks varchar(max),
		listing_broker_name varchar(150),
		listing_broker_id varchar(20),
		listing_agent_name varchar(150),
		listing_agent_id varchar(20),
		listing_agent_phone varchar(10),
		listing_agent_email varchar(100),
		brokerage_name varchar(100),
		brokerage_phone varchar(10),
		selling_agent_name varchar(150),
		selling_agent_id varchar(20),
		commissions varchar(50),
		buyer_agent_name varchar(150),
		buyer_agent_id varchar(20),
		buyer_commission_pct decimal(8,4),
		street_address_raw varchar(100),
		city_raw varchar(100),
		state_raw varchar(50),
		zip_raw varchar(20),
		source varchar(25),
		source_reference varchar(50),
		source_listing_id varchar(50),
		source_as_of_date datetime,
		create_timestamp datetime,
		update_timestamp datetime,
		load_date varchar(10),
		mls varchar(25)
	) ON [PRIMARY] with (data_compression = page)

END
