USE [MLS]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

DROP TABLE IF EXISTS [dbo].[Listing_hadoop]
CREATE TABLE [dbo].[Listing_hadoop](
	[MLS] [varchar](25) NOT NULL,
	[MLSListingID] [varchar](50) NOT NULL,
	[StreetAddress] [varchar](100) NULL,
	[UnitType] [varchar](10) NULL,
	[Unit] [varchar](30) NULL,
	[City] [varchar](100) NULL,
	[State] [char](2) NULL,
	[Zip] [varchar](5) NULL,
	[Latitude] [decimal](10, 6) NULL,
	[Longitude] [decimal](10, 6) NULL,
	[LegalDescription] [varchar](max) NULL,
	[Subdivision] [varchar](100) NULL,
	[Lot] [varchar](15) NULL,
	[Block] [varchar](15) NULL,
	[LegalTract] [varchar](10) NULL,
	[Book] [varchar](25) NULL,
	[Section] [varchar](2) NULL,
	[Township] [varchar](3) NULL,
	[Range] [varchar](3) NULL,
	[APN] [varchar](100) NULL,
	[CountyName] [varchar](50) NULL,
	[FIPS] [varchar](5) NULL,
	[CensusTractGeoID] [varchar](11) NULL,
	[SchoolDistrict] [varchar](125) NULL,
	[PropertyType] [char](2) NULL,
	[PropertySubType] [varchar](20) NULL,
	[PropertyDescription] [varchar](500) NULL,
	[LotSizeAcres] [decimal](11, 3) NULL,
	[LotSizeSqFt] [int] NULL,
	[Zoning] [varchar](250) NULL,
	[Restrictions] [varchar](250) NULL,
	[Easements] [varchar](250) NULL,
	[WaterSource] [varchar](20) NULL,
	[SepticSewer] [varchar](6) NULL,
	[SFHA] [char](1) NULL,
	[GatedCommunity] [char](1) NULL,
	[HOA] [char](1) NULL,
	[HOAName] [varchar](150) NULL,
	[HOAManagementCo] [varchar](250) NULL,
	[HOAManagementCoPhone] [varchar](10) NULL,
	[OccupantType] [varchar](25) NULL,
	[OwnershipType] [varchar](20) NULL,
	[OwnerType] [varchar](25) NULL,
	[OwnerName] [varchar](255) NULL,
	[OwnerPhone] [varchar](10) NULL,
	[YearBuilt] [smallint] NULL,
	[YearUpdated] [smallint] NULL,
	[NumberOfUnits] [smallint] NULL,
	[LivingAreaSqFt] [int] NULL,
	[LivingAreaSqFtSource] [varchar](25) NULL,
	[BuildingStyle] [varchar](100) NULL,
	[Stories] [decimal](6, 2) NULL,
	[Beds] [smallint] NULL,
	[FullBaths] [smallint] NULL,
	[HalfBaths] [smallint] NULL,
	[Basement] [char](1) NULL,
	[FinishedBasementPct] [decimal](4, 0) NULL,
	[GarageType] [char](1) NULL,
	[GarageStyle] [varchar](100) NULL,
	[GarageSpaces] [int] NULL,
	[RoofType] [varchar](255) NULL,
	[ExteriorMaterial] [varchar](255) NULL,
	[Foundation] [varchar](255) NULL,
	[Pool] [varchar](100) NULL,
	[Condition] [varchar](250) NULL,
	[PropertyTaxAppraisal] [decimal](14, 2) NULL,
	[PropertyTax] [decimal](14, 2) NULL,
	[PropertyTaxYear] [smallint] NULL,
	[HOADues] [decimal](14, 2) NULL,
	[HOADuesFrequency] [smallint] NULL,
	[HOADuesDescription] [varchar](750) NULL,
	[RentSale] [char](1) NULL,
	[EntryDate] [date] NULL,
	[ListingDate] [date] NULL,
	[ListingStatus] [char](1) NULL,
	[ListingStatusDetail] [varchar](50) NULL,
	[StatusDate] [date] NULL,
	[CurrentPrice] [decimal](14, 2) NULL,
	[CurrentPriceAsOfDate] [date] NULL,
	[OrigPrice] [decimal](14, 2) NULL,
	[OrigListingDate] [date] NULL,
	[ContractDate] [date] NULL,
	[ClosedPrice] [decimal](14, 2) NULL,
	[ClosedDate] [date] NULL,
	[DaysOnMarket] [int] NULL,
	[DOMDate] [date] NULL,
	[CumulativeDaysOnMarket] [int] NULL,
	[SaleCircumstances] [varchar](max) NULL,
	[ListingConditions] [varchar](max) NULL,
	[ListingURL] [varchar](250) NULL,
	[ListingImageURL] [varchar](max) NULL,
	[ListingImageURLCount] [int] NULL,
	[ListingImageURLDate] [date] NULL,
	[LoanAmount] [decimal](14, 2) NULL,
	[PublicRemarks] [varchar](max) NULL,
	[RealtorRemarks] [varchar](max) NULL,
	[ListingBrokerName] [varchar](150) NULL,
	[ListingBrokerID] [varchar](20) NULL,
	[ListingAgentName] [varchar](150) NULL,
	[ListingAgentID] [varchar](20) NULL,
	[ListingAgentPhone] [varchar](10) NULL,
	[ListingAgentEmail] [varchar](100) NULL,
	[BrokerageName] [varchar](100) NULL,
	[BrokeragePhone] [varchar](10) NULL,
	[SellingAgentName] [varchar](150) NULL,
	[SellingAgentID] [varchar](20) NULL,
	[Commissions] [varchar](50) NULL,
	[BuyerAgentName] [varchar](150) NULL,
	[BuyerAgentID] [varchar](20) NULL,
	[BuyerCommissionPct] [decimal](6, 2) NULL,
	[StreetAddressRaw] [varchar](100) NULL,
	[CityRaw] [varchar](100) NULL,
	[StateRaw] [varchar](50) NULL,
	[ZipRaw] [varchar](20) NULL,
	[AddressCleanedTimeStamp] [datetime2](7) NULL,
	[ailPropertyID] [bigint] NULL,
	[ailSource] [varchar](25) NULL,
	[ailSourceReference] [varchar](50) NULL,
	[ailSourceListingID] [varchar](50) NULL,
	[ailSourceTimeStamp] [datetime2](7) NULL,
	[CreateTimeStamp] [datetime2](7) NOT NULL,
	[UpdateTimeStamp] [datetime2](7) NULL,
	[ListingID] [bigint] NOT NULL,
	[ListingID_Legacy] [bigint] NULL,
	CONSTRAINT [PK_Listing_hadoop] PRIMARY KEY CLUSTERED ([MLS] ASC, [MLSListingID] ASC) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
WITH (DATA_COMPRESSION = PAGE) 
GO

