sqoop eval --connect "jdbc:jtds:sqlserver://$1;useNTLMv2=true;domain=CORP.AMHERST.COM;databaseName=MLSLoad;" \
--username $2 --password $3 \
--query "TRUNCATE TABLE dbo.Listings_sqoop"

sqoop export -Dmapreduce.map.java.opts=' -Duser.timezone=UTC' --connect "jdbc:jtds:sqlserver://$1;useNTLMv2=true;domain=CORP.AMHERST.COM;databaseName=MLSLoad;" \
--username $2 --password $3 \
--table 'Listings_sqoop' \
--hcatalog-database 'mls' \
--hcatalog-table 'listings' \
--columns 'created_datetime, mls_listing_id, street_address, unit_type, unit, city, state, zip, latitude, longitude, legal_description, subdivision, lot, block, legal_tract, book, section, township, range, apn, county_name, fips, census_tract_geo_id, school_district, property_type, property_sub_type, property_description, lot_size_acres, lot_size_sq_ft, zoning, restrictions, easements, water_source, septic_sewer, sfha, gated_community, hoa, hoa_name, hoa_management_co, hoa_management_co_phone, occupant_type, ownership_type, owner_type, owner_name, owner_phone, year_built, year_updated, number_of_units, living_area_sq_ft, living_area_sq_ft_source, building_style, stories, beds, full_baths, half_baths, basement, finished_basement_pct, garage_type, garage_style, garage_spaces, roof_type, exterior_material, foundation, pool, condition, property_tax_appraisal, property_tax, property_tax_year, hoa_dues, hoa_dues_frequency, hoa_dues_description, rent_sale, entry_date, listing_date, listing_status, listing_status_detail, status_date, current_price, current_price_as_of_date, orig_price, orig_listing_date, contract_date, closed_price, closed_date, days_on_market, dom_date, cumulative_days_on_market, sale_circumstances, listing_conditions, listing_url, listing_image_url, listing_image_url_count, listing_image_url_date, loan_amount, public_remarks, realtor_remarks, listing_broker_name, listing_broker_id, listing_agent_name, listing_agent_id, listing_agent_phone, listing_agent_email, brokerage_name, brokerage_phone, selling_agent_name, selling_agent_id, commissions, buyer_agent_name, buyer_agent_id, buyer_commission_pct, street_address_raw, city_raw, state_raw, zip_raw, source, source_reference, source_listing_id, source_as_of_date, create_timestamp, update_timestamp, load_date, mls' \
--map-column-java 'created_datetime=java.sql.Timestamp,legal_description=String,entry_date=java.sql.Date,listing_date=java.sql.Date,status_date=java.sql.Date,current_price_as_of_date=java.sql.Date,orig_listing_date=java.sql.Date,contract_date=java.sql.Date,closed_date=java.sql.Date,dom_date=java.sql.Timestamp,sale_circumstances=String,listing_conditions=String,listing_image_url=String,listing_image_url_date=java.sql.Date,public_remarks=String,realtor_remarks=String,source_as_of_date=java.sql.Timestamp,create_timestamp=java.sql.Timestamp,update_timestamp=java.sql.Timestamp' \
--validate \
-m 2